---
- name: Create backend directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Unarchive file
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend
    remote_src: no

- name: Install app dependencies
  npm:
    path: ~/backend
    state: present

- name: Stop if running
  shell: pm2 stop default

- name: Start application
  shell: pm2 start npm -- start
