- name: Create backend folder
  shell: mkdir /home/ubuntu/backend

- name: Copy zipped file
  copy:
    src: ~/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz
    mode: '0755'
    remote_src: no

- name: Unarchive file
  shell: tar -xzvf artifact.tar.gz ~/backend

  # unarchive:
  #   src: ~/artifact.tar.gz
  #   dest: ~/backend
  #   remote_src: yes

- name: Install app dependencies
  npm:
    path: ~/backend
    state: present

- name: Start application
  shell: cd backend && pm2 start npm -- start
