---

- name: "Create backend folder"
  file:
    path: ~/backend
    state: directory
    mode: '0755'

- name: "Copy zipped file"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz
    mode: '0777'
    remote_src: no

- name: "Unarchive file"
  unarchive:
    src: ~/backend/artifact.tar.gz
    dest: ~/backend
    remote_src: yes

- name: "Install app dependencies"
  npm:
    path: ~/backend
    state: present

- name: "Start application"
  shell: cd ~/backend && pm2 start npm -- start
