---

- name: "Create backend folder"
  shell: mkdir /home/ubuntu/backend

- name: "Copy zipped file"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz
    mode: '0777'
    remote_src: no

- name: "Unarchive file"
  shell: tar -C /home/ubuntu/backend -xzvf artifact.tar.gz

  # unarchive:
  #   src: ~/artifact.tar.gz
  #   dest: ~/backend
  #   remote_src: yes

- name: "Install app dependencies"
  npm:
    path: /home/ubuntu/backend
    state: present

- name: "Start application"
  shell: cd /home/ubuntu/backend && pm2 start npm -- start
