---

- name: Copy artficact to remote host
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    backup: true

- name: Create backend directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Unarchive file
  unarchive:
    remote_src: yes
    dest: ~/backend

- name: Install app dependencies
  npm:
    path: ~/backend
    state: present

- name: Stop if running
  shell: pm2 stop default

- name: Start application
  shell: pm2 start npm -- start
