---
- name: Copy zipped file
  copy:
    src: artifact.tar.gz
    dest: ~/
    mode: '0755'
    remote_src: no

- name: Unarchive file
  command: tar -xzvf artifact.tar.gz backend
  # unarchive:
  #   src: ~/artifact.tar.gz
  #   dest: ~/backend
  #   remote_src: yes

- name: Install app dependencies
  npm:
    path: ~/backend
    state: present

- name: Start application
  shell: cd backend && pm2 start npm -- start
