version: 2.1

jobs:
  build_frontend:
    docker:
      - image: cimg/node:13.8
    steps:
      - checkout
      - restore_cache:
          key: frontend-node-modules
      - run:
          name: Build and Compile Frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-node-modules

  build_backend:
    docker:
      - image: cimg/node:13.8
    steps:
      - checkout
      - restore_cache:
          key: backend-node-modules
      - run:
          name: Build and Compile Backend
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-node-modules

workflows:
  default:
    jobs:
      - build_frontend
      - build_backend
